print('Hello World🤩')
print('Nada no mundo é mais perigoso que a ignorância sincera e a estupidez consciente')
print('A liberdade jamais é dada pelo opressor ela tem que ser conquistada pelo oprimido')
print('A inteligência e o caráter são os objetivos da verdadeira educação')
print('Acenda um farol')
print('O telefone tocou novamente - Jorge Ben Jor')
print('E não importa quem vai chegar em primeiro E sim onde tu quer chegar? qual tua meta Mostra - BK')
print('O flash te cega por uns segundos, mas o viciado em brilho é eternamente ofuscado')
print('Money, cash')
print('Oba, la vem ela  ')